// data/rejectionReasonsData.ts

export interface RejectionReason {
    id: string;
    reason: string;
    count: number;
    percentage: string;
    color: string;
    desc: string;
}

export const rejectionReasonsData: RejectionReason[] = [
    { id: "r001", reason: "Account number not linked with given debit card", count: 13879, percentage: "0.71%", color: "#C9DEFF", desc: "BUSINESS DECLINE" },
    { id: "r002", reason: "Customer mobile number not available in bank CBS to trigger OTP", count: 29878, percentage: "1.53%", color: "#C9DEFF", desc: "BUSINESS DECLINE" },
    { id: "r003", reason: "No such account in CBS / Invalid account number", count: 45078, percentage: "2.31%", color: "#C9DEFF", desc: "BUSINESS DECLINE" },
    { id: "r004", reason: "Authentication failed due to invalid net banking credentials", count: 3883, percentage: "0.20%", color: "#C9DEFF", desc: "BUSINESS DECLINE" },
    { id: "r005", reason: "Mandate registration not allowed for minor account", count: 3552, percentage: "0.18%", color: "#C9DEFF", desc: "BUSINESS DECLINE" },
    { id: "r006", reason: "Mandate registration not allowed for NRE account", count: 10463, percentage: "0.54%", color: "#C9DEFF", desc: "BUSINESS DECLINE" },
    { id: "r007", reason: "Mandate registration not allowed - Account freeze by court/attachment order", count: 10645, percentage: "0.55%", color: "#C9DEFF", desc: "BUSINESS DECLINE" },
    { id: "r008", reason: "Invalid mandate frequency", count: 13789, percentage: "0.71%", color: "#C9DEFF", desc: "BUSINESS DECLINE" },
    { id: "r009", reason: "Account number registered for only view rights in net banking", count: 14769, percentage: "0.76%", color: "#C9DEFF", desc: "BUSINESS DECLINE" },
    { id: "r010", reason: "Account inactive", count: 15890, percentage: "0.81%", color: "#C9DEFF", desc: "BUSINESS DECLINE" },
    { id: "r011", reason: "Invalid debit card details", count: 30898, percentage: "1.58%", color: "#C9DEFF", desc: "BUSINESS DECLINE" },
    { id: "r012", reason: "Invalid bank OTP", count: 19876, percentage: "1.02%", color: "#C9DEFF", desc: "BUSINESS DECLINE" },
    { id: "r013", reason: "Account number not registered with net banking facility", count: 74890, percentage: "3.84%", color: "#C9DEFF", desc: "BUSINESS DECLINE" },
    { id: "r014", reason: "Maximum tries exceeded for bank OTP", count: 40705, percentage: "2.08%", color: "#C9DEFF", desc: "BUSINESS DECLINE" },
    { id: "r015", reason: "Could not send OTP to customer", count: 5067, percentage: "0.26%", color: "#C9DEFF", desc: "BUSINESS DECLINE" },
    { id: "r016", reason: "Account blocked", count: 29878, percentage: "1.53%", color: "#C9DEFF", desc: "BUSINESS DECLINE" },
    { id: "r017", reason: "Account closed", count: 10988, percentage: "0.56%", color: "#C9DEFF", desc: "BUSINESS DECLINE" },
    { id: "r018", reason: "Account frozen", count: 8907, percentage: "0.46%", color: "#C9DEFF", desc: "BUSINESS DECLINE" },
    { id: "r019", reason: "Account inoperative", count: 11879, percentage: "0.61%", color: "#C9DEFF", desc: "BUSINESS DECLINE" },
    { id: "r020", reason: "Refer to the branch - KYC not completed", count: 7098, percentage: "0.36%", color: "#C9DEFF", desc: "BUSINESS DECLINE" },
    { id: "r021", reason: "Account holder name mismatch with CBS", count: 40876, percentage: "2.09%", color: "#C9DEFF", desc: "BUSINESS DECLINE" },
    { id: "r022", reason: "Account type in mandate is different from CBS", count: 15790, percentage: "0.81%", color: "#C9DEFF", desc: "BUSINESS DECLINE" },
    { id: "r023", reason: "Amount of EMI more than limit allowed for the account", count: 30786, percentage: "1.58%", color: "#C9DEFF", desc: "BUSINESS DECLINE" },
    { id: "r024", reason: "Mandate registration not allowed for CC account", count: 15347, percentage: "0.79%", color: "#C9DEFF", desc: "BUSINESS DECLINE" },
    { id: "r025", reason: "Mandate registration not allowed for PF account", count: 4589, percentage: "0.24%", color: "#C9DEFF", desc: "BUSINESS DECLINE" },
    { id: "r026", reason: "Mandate registration not allowed for PPF account", count: 5676, percentage: "0.29%", color: "#C9DEFF", desc: "BUSINESS DECLINE" },
    { id: "r027", reason: "Mandate registration not allowed for Joint account", count: 12064, percentage: "0.62%", color: "#C9DEFF", desc: "BUSINESS DECLINE" },
    { id: "r028", reason: "Mandate registration not allowed for wallet account", count: 3084, percentage: "0.16%", color: "#C9DEFF", desc: "BUSINESS DECLINE" },
    { id: "r029", reason: "Debit card blocked", count: 10987, percentage: "0.56%", color: "#C9DEFF", desc: "BUSINESS DECLINE" },
    { id: "r030", reason: "Debit card hot listed", count: 6088, percentage: "0.31%", color: "#C9DEFF", desc: "BUSINESS DECLINE" },
    { id: "r031", reason: "Debit card expired", count: 5789, percentage: "0.30%", color: "#C9DEFF", desc: "BUSINESS DECLINE" },
    { id: "r032", reason: "Maximum tries exceeded for UIDAI OTP", count: 17644, percentage: "0.90%", color: "#C9DEFF", desc: "BUSINESS DECLINE" },
    { id: "r033", reason: "Transaction value did not match with transaction value of request OTP API", count: 7654, percentage: "0.39%", color: "#C9DEFF", desc: "BUSINESS DECLINE" },
    { id: "r034", reason: "Maximum number of attempts for OTP match is exceeded or OTP is not generated", count: 22764, percentage: "1.17%", color: "#C9DEFF", desc: "BUSINESS DECLINE" },
    { id: "r035", reason: "Debit card not activated", count: 29878, percentage: "1.53%", color: "#C9DEFF", desc: "BUSINESS DECLINE" },
    { id: "r036", reason: "Drawers signature differs", count: 35879, percentage: "1.84%", color: "#C9DEFF", desc: "BUSINESS DECLINE" },
    { id: "r037", reason: "Data mismatch with image - account number", count: 18675, percentage: "0.96%", color: "#C9DEFF", desc: "BUSINESS DECLINE" },
    { id: "r038", reason: "Data mismatch with image - amount", count: 16390, percentage: "0.84%", color: "#C9DEFF", desc: "BUSINESS DECLINE" },
    { id: "r039", reason: "Data mismatch with image - Corporate name mismatch", count: 15480, percentage: "0.79%", color: "#C9DEFF", desc: "BUSINESS DECLINE" },
    { id: "r040", reason: "Data mismatch with image - debtor bank name", count: 56479, percentage: "2.89%", color: "#C9DEFF", desc: "BUSINESS DECLINE" },
    { id: "r041", reason: "Data mismatch with image - end date", count: 29878, percentage: "1.53%", color: "#C9DEFF", desc: "BUSINESS DECLINE" },
    { id: "r042", reason: "Data mismatch with image - more than one field", count: 60987, percentage: "3.12%", color: "#C9DEFF", desc: "BUSINESS DECLINE" },
    { id: "r043", reason: "Data mismatch with image - period", count: 29878, percentage: "1.53%", color: "#C9DEFF", desc: "BUSINESS DECLINE" },
    { id: "r044", reason: "Data mismatch with image - start date", count: 30857, percentage: "1.58%", color: "#C9DEFF", desc: "BUSINESS DECLINE" },
    { id: "r045", reason: "Refer to the branch - KYC not completed", count: 55890, percentage: "2.86%", color: "#C9DEFF", desc: "BUSINESS DECLINE" },
    { id: "r046", reason: "Rejected as per customer confirmation", count: 10380, percentage: "0.53%", color: "#C9DEFF", desc: "BUSINESS DECLINE" },
    { id: "r047", reason: "Debit card not activated", count: 29878, percentage: "1.53%", color: "#C9DEFF", desc: "BUSINESS DECLINE" },
    { id: "r048", reason: "Debit card Hot listed", count: 29878, percentage: "1.53%", color: "#C9DEFF", desc: "BUSINESS DECLINE" },
    { id: "r049", reason: "Cust ID validation failed due to Customer ID mismatch with CBS", count: 6645, percentage: "0.34%", color: "#C9DEFF", desc: "BUSINESS DECLINE" },
    { id: "r050", reason: "PAN validation failed due to PAN number mismatch with CBS", count: 3984, percentage: "0.20%", color: "#C9DEFF", desc: "BUSINESS DECLINE" },
    { id: "r051", reason: "PAN validation failed due to PAN not updated in CBS", count: 3536, percentage: "0.18%", color: "#C9DEFF", desc: "BUSINESS DECLINE" },
    { id: "r052", reason: "Aadhaar number not linked with the debtor account number", count: 23467, percentage: "1.20%", color: "#C9DEFF", desc: "BUSINESS DECLINE" },
    { id: "r053", reason: "Aadhaar number does not have mobile number in UIDAI", count: 13487, percentage: "0.69%", color: "#C9DEFF", desc: "BUSINESS DECLINE" },
    { id: "r054", reason: "UIDAI authentication failed due to invalid Aadhaar OTP", count: 13574, percentage: "0.70%", color: "#C9DEFF", desc: "BUSINESS DECLINE" },
    { id: "r055", reason: "Aadhaar number does not match with debtor account number", count: 29878, percentage: "1.53%", color: "#C9DEFF", desc: "BUSINESS DECLINE" },
    { id: "r056", reason: "Aadhaar number does not have both email id and mobile number", count: 15476, percentage: "0.79%", color: "#C9DEFF", desc: "BUSINESS DECLINE" },
    { id: "r057", reason: "Aadhaar number doesn't have verified mobile number", count: 12357, percentage: "0.63%", color: "#C9DEFF", desc: "BUSINESS DECLINE" },
    { id: "r058", reason: "Aadhaar number doesn't have verified email and mobile number", count: 13765, percentage: "0.71%", color: "#C9DEFF", desc: "BUSINESS DECLINE" },
    { id: "r059", reason: "Aadhaar locked by Aadhaar number holder", count: 6548, percentage: "0.34%", color: "#C9DEFF", desc: "BUSINESS DECLINE" },
    { id: "r060", reason: "Aadhaar number usage is blocked by Aadhaar number holder", count: 7655, percentage: "0.39%", color: "#C9DEFF", desc: "BUSINESS DECLINE" },
    { id: "r061", reason: "Aadhaar not mapped to account number", count: 36549, percentage: "1.87%", color: "#C9DEFF", desc: "BUSINESS DECLINE" },
    { id: "r062", reason: "Aadhaar number does not have mobile number in UIDAI", count: 29847, percentage: "1.53%", color: "#C9DEFF", desc: "BUSINESS DECLINE" },
    { id: "r063", reason: "No response received from bank within prescribed time limit", count: 8676, percentage: "0.44%", color: "#EAF2FF", desc: "TECHNICAL DECLINE" },
    { id: "r064", reason: "Invalid UIDAI authentication flag received for defined mandate limit", count: 29878, percentage: "1.53%", color: "#EAF2FF", desc: "TECHNICAL DECLINE" },
    { id: "r065", reason: "Time expired for UIDAI OTP", count: 2803, percentage: "0.14%", color: "#EAF2FF", desc: "TECHNICAL DECLINE" },
    { id: "r066", reason: "No response received from customer during mandate registration", count: 40678, percentage: "2.08%", color: "#EAF2FF", desc: "TECHNICAL DECLINE" },
    { id: "r067", reason: "Time expired for bank OTP", count: 30650, percentage: "1.57%", color: "#EAF2FF", desc: "TECHNICAL DECLINE" },
    { id: "r068", reason: "Technical error or connectivity issues at bank end", count: 60765, percentage: "3.11%", color: "#EAF2FF", desc: "TECHNICAL DECLINE" },
    { id: "r069", reason: "Transaction rejected or cancelled by the customer", count: 16870, percentage: "0.86%", color: "#EAF2FF", desc: "TECHNICAL DECLINE" },
    { id: "r070", reason: "Browser closed by customer in mid transaction", count: 29878, percentage: "1.53%", color: "#EAF2FF", desc: "TECHNICAL DECLINE" },
    { id: "r071", reason: "User rejected the transaction on pre-login page", count: 35787, percentage: "1.83%", color: "#EAF2FF", desc: "TECHNICAL DECLINE" },
    { id: "r072", reason: "Unknown error", count: 45738, percentage: "2.34%", color: "#EAF2FF", desc: "TECHNICAL DECLINE" },
    { id: "r073", reason: "Bank return error XML", count: 35479, percentage: "1.82%", color: "#EAF2FF", desc: "TECHNICAL DECLINE" },
    { id: "r074", reason: "No response received from bank within prescribed API time limit", count: 18649, percentage: "0.96%", color: "#EAF2FF", desc: "TECHNICAL DECLINE" },
    { id: "r075", reason: "Technical errors or connectivity issues at bank end", count: 45390, percentage: "2.32%", color: "#EAF2FF", desc: "TECHNICAL DECLINE" },
    { id: "r076", reason: "An unmapped error/reason code was sent by the bank", count: 11865, percentage: "0.61%", color: "#EAF2FF", desc: "TECHNICAL DECLINE" },
    { id: "r077", reason: "Bank Signature validation failed", count: 20645, percentage: "1.06%", color: "#EAF2FF", desc: "TECHNICAL DECLINE" },
    { id: "r078", reason: "Time expired for OTP", count: 13765, percentage: "0.71%", color: "#EAF2FF", desc: "TECHNICAL DECLINE" },
    { id: "r079", reason: "Maximum tries exceeded for OTP", count: 20987, percentage: "1.07%", color: "#EAF2FF", desc: "TECHNICAL DECLINE" },
    { id: "r080", reason: "Merchant CheckSum empty or not available", count: 29534, percentage: "1.51%", color: "#EAF2FF", desc: "TECHNICAL DECLINE" },
    { id: "r081", reason: "Invalid User Credentials", count: 59460, percentage: "3.05%", color: "#EAF2FF", desc: "TECHNICAL DECLINE" },
    { id: "r082", reason: "Invalid bank response received", count: 35786, percentage: "1.83%", color: "#EAF2FF", desc: "TECHNICAL DECLINE" },
    { id: "r083", reason: "Error occurred at NPCI", count: 49870, percentage: "2.55%", color: "#EAF2FF", desc: "TECHNICAL DECLINE" },
    { id: "r084", reason: "Bank Aadhaar OTP verification response failed", count: 29878, percentage: "1.53%", color: "#EAF2FF", desc: "TECHNICAL DECLINE" },
    { id: "r085", reason: "Aadhaar Number mismatch in X509cert and bank CBS", count: 10984, percentage: "0.56%", color: "#EAF2FF", desc: "TECHNICAL DECLINE" },
];

// Total mandate count from source: 1952340 (100.00%)
export const totalMandateCount = 1952340;