// data/rejectionReasonsData.ts

export interface RejectionReason {
    id: string;
    reason: string;
    count: number;
    percentage: string;
    color: string;
    desc: string;
}

export const rejectionReasonsData: RejectionReason[] = [
    { id: "r001", reason: "Aadhaar number does not match with debtor account number", count: 385, percentage: "3.71%", color: "#C9DEFF", desc: "BUSINESS DECLINE" },
    { id: "r002", reason: "Aadhaar number not linked with the debtor account number", count: 1622, percentage: "15.61%", color: "#C9DEFF", desc: "BUSINESS DECLINE" },
    { id: "r003", reason: "Account frozen", count: 276, percentage: "2.66%", color: "#C9DEFF", desc: "BUSINESS DECLINE" },
    { id: "r004", reason: "Account holder name mismatch with CBS", count: 337, percentage: "3.24%", color: "#C9DEFF", desc: "BUSINESS DECLINE" },
    { id: "r005", reason: "Browser closed by the customer", count: 1092, percentage: "10.51%", color: "#C9DEFF", desc: "BUSINESS DECLINE" },
    { id: "r006", reason: "Drawers signature differs", count: 473, percentage: "4.55%", color: "#C9DEFF", desc: "BUSINESS DECLINE" },
    { id: "r007", reason: "Mandate registration not allowed for joint account", count: 286, percentage: "2.75%", color: "#C9DEFF", desc: "BUSINESS DECLINE" },
    { id: "r008", reason: "No response received from bank within prescribed API time limit", count: 634, percentage: "6.10%", color: "#C9DEFF", desc: "BUSINESS DECLINE" },
    { id: "r009", reason: "No such account", count: 494, percentage: "4.75%", color: "#C9DEFF", desc: "BUSINESS DECLINE" },
    { id: "r010", reason: "Technical errors or connectivity issues at bank end", count: 814, percentage: "7.83%", color: "#C9DEFF", desc: "BUSINESS DECLINE" },
    { id: "r011", reason: "Transaction rejected or cancelled by the customer", count: 660, percentage: "6.35%", color: "#C9DEFF", desc: "BUSINESS DECLINE" },
    { id: "r012", reason: "Aadhaar not mapped to account number", count: 33, percentage: "0.32%", color: "#C9DEFF", desc: "BUSINESS DECLINE" },
    { id: "r013", reason: "Aadhaar number does not have mobile number in UIDAI", count: 125, percentage: "1.20%", color: "#C9DEFF", desc: "BUSINESS DECLINE" },
    { id: "r014", reason: "Aadhaar number mismatch in X509 cert and bank CBS", count: 6, percentage: "0.06%", color: "#C9DEFF", desc: "BUSINESS DECLINE" },
    { id: "r015", reason: "Aadhaar number mismatch in X509 cert and mandate", count: 1, percentage: "0.01%", color: "#C9DEFF", desc: "BUSINESS DECLINE" },
    { id: "r016", reason: "Account blocked", count: 36, percentage: "0.35%", color: "#C9DEFF", desc: "BUSINESS DECLINE" },
    { id: "r017", reason: "Account closed", count: 11, percentage: "0.11%", color: "#C9DEFF", desc: "BUSINESS DECLINE" },
    { id: "r018", reason: "Account details does not match", count: 4, percentage: "0.04%", color: "#C9DEFF", desc: "BUSINESS DECLINE" },
    { id: "r019", reason: "Account frozen or blocked", count: 38, percentage: "0.37%", color: "#C9DEFF", desc: "BUSINESS DECLINE" },
    { id: "r020", reason: "Account inactive", count: 19, percentage: "0.18%", color: "#C9DEFF", desc: "BUSINESS DECLINE" },
    { id: "r021", reason: "Account inoperative", count: 152, percentage: "1.46%", color: "#C9DEFF", desc: "BUSINESS DECLINE" },
    { id: "r022", reason: "Account number not linked with given debit card", count: 21, percentage: "0.20%", color: "#C9DEFF", desc: "BUSINESS DECLINE" },
    { id: "r023", reason: "Account number not registered with net banking facility", count: 26, percentage: "0.25%", color: "#C9DEFF", desc: "BUSINESS DECLINE" },
    { id: "r024", reason: "Account number registered for only view rights in net banking", count: 9, percentage: "0.09%", color: "#C9DEFF", desc: "BUSINESS DECLINE" },
    { id: "r025", reason: "Account type in mandate is different from CBS", count: 58, percentage: "0.56%", color: "#C9DEFF", desc: "BUSINESS DECLINE" },
    { id: "r026", reason: "Account type in mandate is different from CBS", count: 10, percentage: "0.10%", color: "#C9DEFF", desc: "BUSINESS DECLINE" },
    { id: "r027", reason: "Alterations require drawers authentication", count: 1, percentage: "0.01%", color: "#C9DEFF", desc: "BUSINESS DECLINE" },
    { id: "r028", reason: "Amount of EMI more than limit allowed for the account", count: 1, percentage: "0.01%", color: "#C9DEFF", desc: "BUSINESS DECLINE" },
    { id: "r029", reason: "Amount of EMI more than limit allowed for the account", count: 43, percentage: "0.41%", color: "#C9DEFF", desc: "BUSINESS DECLINE" },
    { id: "r030", reason: "An unmapped error/reason code was sent by the bank", count: 251, percentage: "2.42%", color: "#C9DEFF", desc: "BUSINESS DECLINE" },
    { id: "r031", reason: "Appropriate NACH mandate not uploaded", count: 1, percentage: "0.01%", color: "#C9DEFF", desc: "BUSINESS DECLINE" },
    { id: "r032", reason: "Authentication failed", count: 19, percentage: "0.18%", color: "#C9DEFF", desc: "BUSINESS DECLINE" },
    { id: "r033", reason: "Authentication failed due to invalid net banking credentials", count: 9, percentage: "0.09%", color: "#C9DEFF", desc: "BUSINESS DECLINE" },
    { id: "r034", reason: "Authentication failed", count: 4, percentage: "0.04%", color: "#C9DEFF", desc: "BUSINESS DECLINE" },
    { id: "r035", reason: "Bank Aadhaar OTP verification response failed", count: 4, percentage: "0.04%", color: "#C9DEFF", desc: "BUSINESS DECLINE" },
    { id: "r036", reason: "Bank MsgId is duplicate", count: 2, percentage: "0.02%", color: "#C9DEFF", desc: "BUSINESS DECLINE" },
    { id: "r037", reason: "Bank signature validation failed", count: 32, percentage: "0.31%", color: "#C9DEFF", desc: "BUSINESS DECLINE" },
    { id: "r038", reason: "Bank return error XML", count: 3, percentage: "0.03%", color: "#C9DEFF", desc: "BUSINESS DECLINE" },
    { id: "r039", reason: "Browser closed by customer in mid transaction", count: 47, percentage: "0.45%", color: "#C9DEFF", desc: "BUSINESS DECLINE" },
    { id: "r040", reason: "Company for stamp required or wrong", count: 9, percentage: "0.09%", color: "#C9DEFF", desc: "BUSINESS DECLINE" },
    { id: "r041", reason: "Could not send OTP to customer", count: 1, percentage: "0.01%", color: "#C9DEFF", desc: "BUSINESS DECLINE" },
    { id: "r042", reason: "Currently your bank is not responding, please try again after sometime", count: 1, percentage: "0.01%", color: "#C9DEFF", desc: "BUSINESS DECLINE" },
    { id: "r043", reason: "Customer ID validation failed due to customer ID mismatch with CBS", count: 18, percentage: "0.17%", color: "#C9DEFF", desc: "BUSINESS DECLINE" },
    { id: "r044", reason: "Customer mobile number not available in bank CBS to trigger OTP", count: 129, percentage: "1.24%", color: "#C9DEFF", desc: "BUSINESS DECLINE" },
    { id: "r045", reason: "Data mismatch with image - account number", count: 1, percentage: "0.01%", color: "#C9DEFF", desc: "BUSINESS DECLINE" },
    { id: "r046", reason: "Data mismatch with image - amount", count: 3, percentage: "0.03%", color: "#C9DEFF", desc: "BUSINESS DECLINE" },
    { id: "r047", reason: "Data mismatch with image - corporate name mismatch", count: 1, percentage: "0.01%", color: "#C9DEFF", desc: "BUSINESS DECLINE" },
    { id: "r048", reason: "Data mismatch with image - debtor bank name", count: 7, percentage: "0.07%", color: "#C9DEFF", desc: "BUSINESS DECLINE" },
    { id: "r049", reason: "Data mismatch with image - end date", count: 2, percentage: "0.02%", color: "#C9DEFF", desc: "BUSINESS DECLINE" },
    { id: "r050", reason: "Data mismatch with image - more than one field", count: 8, percentage: "0.08%", color: "#C9DEFF", desc: "BUSINESS DECLINE" },
    { id: "r051", reason: "Data mismatch with image - period", count: 1, percentage: "0.01%", color: "#C9DEFF", desc: "BUSINESS DECLINE" },
    { id: "r052", reason: "Data mismatch with image - start date", count: 1, percentage: "0.01%", color: "#C9DEFF", desc: "BUSINESS DECLINE" },
    { id: "r053", reason: "Debit card blocked", count: 10, percentage: "0.10%", color: "#C9DEFF", desc: "BUSINESS DECLINE" },
    { id: "r054", reason: "Debit card hotlisted", count: 3, percentage: "0.03%", color: "#C9DEFF", desc: "BUSINESS DECLINE" },
    { id: "r055", reason: "Debit card not activated", count: 23, percentage: "0.22%", color: "#C9DEFF", desc: "BUSINESS DECLINE" },
    { id: "r056", reason: "Debit card not activated", count: 114, percentage: "1.10%", color: "#C9DEFF", desc: "BUSINESS DECLINE" },
    { id: "r057", reason: "Debit card validation failed due to invalid CVV", count: 6, percentage: "0.06%", color: "#C9DEFF", desc: "BUSINESS DECLINE" },
    { id: "r058", reason: "Debit card validation failed due to invalid PIN", count: 68, percentage: "0.65%", color: "#C9DEFF", desc: "BUSINESS DECLINE" },
    { id: "r059", reason: "Debit card validation failed due to invalid expiry", count: 1, percentage: "0.01%", color: "#C9DEFF", desc: "BUSINESS DECLINE" },
    { id: "r060", reason: "Drawers signature illegible in mandate form", count: 8, percentage: "0.08%", color: "#C9DEFF", desc: "BUSINESS DECLINE" },
    { id: "r061", reason: "Drawers signature required", count: 2, percentage: "0.02%", color: "#C9DEFF", desc: "BUSINESS DECLINE" },
    { id: "r062", reason: "Duplicate bank response", count: 1, percentage: "0.01%", color: "#C9DEFF", desc: "BUSINESS DECLINE" },
    { id: "r063", reason: "Error in decrypting Accepted value", count: 23, percentage: "0.22%", color: "#C9DEFF", desc: "BUSINESS DECLINE" },
    { id: "r064", reason: "Error in decrypting FrstColltnDt", count: 3, percentage: "0.03%", color: "#C9DEFF", desc: "BUSINESS DECLINE" },
    { id: "r065", reason: "Error in processing Aadhaar generate OTP", count: 2, percentage: "0.02%", color: "#C9DEFF", desc: "BUSINESS DECLINE" },
    { id: "r066", reason: "Error in processing Aadhaar verify OTP", count: 2, percentage: "0.02%", color: "#C9DEFF", desc: "BUSINESS DECLINE" },
    { id: "r067", reason: "Error occurred at NPCI", count: 186, percentage: "1.79%", color: "#C9DEFF", desc: "BUSINESS DECLINE" },
    { id: "r068", reason: "Image not clear", count: 15, percentage: "0.14%", color: "#C9DEFF", desc: "BUSINESS DECLINE" },
    { id: "r069", reason: "Invalid Aadhaar number or virtual ID", count: 18, percentage: "0.17%", color: "#C9DEFF", desc: "BUSINESS DECLINE" },
    { id: "r070", reason: "Invalid bank OTP", count: 102, percentage: "0.98%", color: "#C9DEFF", desc: "BUSINESS DECLINE" },
    { id: "r071", reason: "Invalid bank response received", count: 108, percentage: "1.04%", color: "#C9DEFF", desc: "BUSINESS DECLINE" },
    { id: "r072", reason: "Invalid CVV", count: 3, percentage: "0.03%", color: "#EAF2FF", desc: "TECHNICAL DECLINE" },
    { id: "r073", reason: "Invalid debit card details", count: 208, percentage: "2.00%", color: "#EAF2FF", desc: "TECHNICAL DECLINE" },
    { id: "r074", reason: "Invalid debit card number", count: 2, percentage: "0.02%", color: "#EAF2FF", desc: "TECHNICAL DECLINE" },
    { id: "r075", reason: "Invalid frequency", count: 4, percentage: "0.04%", color: "#EAF2FF", desc: "TECHNICAL DECLINE" },
    { id: "r076", reason: "Invalid UIDAI authentication flag received for defined mandate limit", count: 3, percentage: "0.03%", color: "#EAF2FF", desc: "TECHNICAL DECLINE" },
    { id: "r077", reason: "Invalid request", count: 6, percentage: "0.06%", color: "#EAF2FF", desc: "TECHNICAL DECLINE" },
    { id: "r078", reason: "Invalid user credentials", count: 84, percentage: "0.81%", color: "#EAF2FF", desc: "TECHNICAL DECLINE" },
    { id: "r079", reason: "Joint signature required", count: 3, percentage: "0.03%", color: "#EAF2FF", desc: "TECHNICAL DECLINE" },
    { id: "r080", reason: "M003 - Drawers signature differs", count: 1, percentage: "0.01%", color: "#EAF2FF", desc: "TECHNICAL DECLINE" },
    { id: "r081", reason: "M026 - Account frozen", count: 1, percentage: "0.01%", color: "#EAF2FF", desc: "TECHNICAL DECLINE" },
    { id: "r082", reason: "M060 - Invalid frequency", count: 1, percentage: "0.01%", color: "#EAF2FF", desc: "TECHNICAL DECLINE" },
    { id: "r083", reason: "Mandate not registered - not maintaining required balance", count: 65, percentage: "0.63%", color: "#EAF2FF", desc: "TECHNICAL DECLINE" },
    { id: "r084", reason: "Mandate not registered - minor account", count: 11, percentage: "0.11%", color: "#EAF2FF", desc: "TECHNICAL DECLINE" },
    { id: "r085", reason: "Mandate not registered - NRE account", count: 1, percentage: "0.01%", color: "#EAF2FF", desc: "TECHNICAL DECLINE" },
    { id: "r086", reason: "Mandate registration failed, please contact your home branch", count: 57, percentage: "0.55%", color: "#EAF2FF", desc: "TECHNICAL DECLINE" },
    { id: "r087", reason: "Mandate registration failed, please contact your home branch", count: 15, percentage: "0.14%", color: "#EAF2FF", desc: "TECHNICAL DECLINE" },
    { id: "r088", reason: "Mandate registration not allowed for CC account", count: 30, percentage: "0.29%", color: "#EAF2FF", desc: "TECHNICAL DECLINE" },
    { id: "r089", reason: "Mandate registration not allowed for minor account", count: 9, percentage: "0.09%", color: "#EAF2FF", desc: "TECHNICAL DECLINE" },
    { id: "r090", reason: "Mandate registration not allowed for PPF account", count: 3, percentage: "0.03%", color: "#EAF2FF", desc: "TECHNICAL DECLINE" },
    { id: "r091", reason: "Mandate registration not allowed for NRE account", count: 1, percentage: "0.01%", color: "#EAF2FF", desc: "TECHNICAL DECLINE" },
    { id: "r092", reason: "Maximum number of attempts for OTP match is exceeded or OTP is not generated", count: 8, percentage: "0.08%", color: "#EAF2FF", desc: "TECHNICAL DECLINE" },
    { id: "r093", reason: "Maximum number of attempts for OTP match is exceeded or OTP is not generated", count: 17, percentage: "0.16%", color: "#EAF2FF", desc: "TECHNICAL DECLINE" },
    { id: "r094", reason: "Maximum tries exceeded for bank OTP", count: 15, percentage: "0.14%", color: "#EAF2FF", desc: "TECHNICAL DECLINE" },
    { id: "r095", reason: "Maximum tries exceeded for OTP", count: 75, percentage: "0.72%", color: "#EAF2FF", desc: "TECHNICAL DECLINE" },
    { id: "r096", reason: "Merchant checksum empty or not available", count: 2, percentage: "0.02%", color: "#EAF2FF", desc: "TECHNICAL DECLINE" },
    { id: "r097", reason: "Merchant Xmlns name empty or incorrect", count: 7, percentage: "0.07%", color: "#EAF2FF", desc: "TECHNICAL DECLINE" },
    { id: "r098", reason: "No response received from customer during mandate registration", count: 6, percentage: "0.06%", color: "#EAF2FF", desc: "TECHNICAL DECLINE" },
    { id: "r099", reason: "No response received from customer during mandate registration", count: 98, percentage: "0.94%", color: "#EAF2FF", desc: "TECHNICAL DECLINE" },
    { id: "r100", reason: "No response received from customer during mandate registration", count: 158, percentage: "1.52%", color: "#EAF2FF", desc: "TECHNICAL DECLINE" },
    { id: "r101", reason: "No such account in CBS / invalid account number", count: 89, percentage: "0.86%", color: "#EAF2FF", desc: "TECHNICAL DECLINE" },
    { id: "r102", reason: "OTP flooding error", count: 3, percentage: "0.03%", color: "#EAF2FF", desc: "TECHNICAL DECLINE" },
    { id: "r103", reason: "OTP store related technical error", count: 6, percentage: "0.06%", color: "#EAF2FF", desc: "TECHNICAL DECLINE" },
    { id: "r104", reason: "OTP verification failure", count: 10, percentage: "0.10%", color: "#EAF2FF", desc: "TECHNICAL DECLINE" },
    { id: "r105", reason: "OTP verify details response is null", count: 21, percentage: "0.20%", color: "#EAF2FF", desc: "TECHNICAL DECLINE" },
    { id: "r106", reason: "Present under proper mandate category", count: 1, percentage: "0.01%", color: "#EAF2FF", desc: "TECHNICAL DECLINE" },
    { id: "r107", reason: "Refer to the branch - KYC not completed", count: 17, percentage: "0.16%", color: "#EAF2FF", desc: "TECHNICAL DECLINE" },
    { id: "r108", reason: "Rejected as per customer confirmation", count: 2, percentage: "0.02%", color: "#EAF2FF", desc: "TECHNICAL DECLINE" },
    { id: "r109", reason: "Thumb impression in CBS but customer sign in mandate", count: 3, percentage: "0.03%", color: "#EAF2FF", desc: "TECHNICAL DECLINE" },
    { id: "r110", reason: "Time expired for bank OTP", count: 6, percentage: "0.06%", color: "#EAF2FF", desc: "TECHNICAL DECLINE" },
    { id: "r111", reason: "Time expired for OTP", count: 52, percentage: "0.50%", color: "#EAF2FF", desc: "TECHNICAL DECLINE" },
    { id: "r112", reason: "Transaction value did not match with transaction value of request OTP API", count: 2, percentage: "0.02%", color: "#EAF2FF", desc: "TECHNICAL DECLINE" },
    { id: "r113", reason: "UIDAI authentication failed due to invalid Aadhaar OTP", count: 131, percentage: "1.26%", color: "#EAF2FF", desc: "TECHNICAL DECLINE" },
    { id: "r114", reason: "Unknown error", count: 31, percentage: "0.30%", color: "#EAF2FF", desc: "TECHNICAL DECLINE" },
    { id: "r115", reason: "Unknown error", count: 10, percentage: "0.10%", color: "#EAF2FF", desc: "TECHNICAL DECLINE" },
    { id: "r116", reason: "User rejected the transaction on pre-login page", count: 23, percentage: "0.22%", color: "#EAF2FF", desc: "TECHNICAL DECLINE" },
    { id: "r117", reason: "Withdrawal stopped owing to death of account holder", count: 90, percentage: "0.87%", color: "#EAF2FF", desc: "TECHNICAL DECLINE" },
    { id: "r118", reason: "Withdrawal stopped owing to insolvency of account", count: 76, percentage: "0.71%", color: "#EAF2FF", desc: "TECHNICAL DECLINE" },
    { id: "r119", reason: "Withdrawal stopped owing to insolvency of account", count: 8, percentage: "0.04%", color: "#EAF2FF", desc: "TECHNICAL DECLINE" },
];

// Total mandate count from source: 10391 (100.00%)
export const totalMandateCount = 10391;